### ISSUE TITLE
Revise all lectures to use the style guide

### ISSUE THREAD

**Issue by luk3b** [luk3b/kit-lecture-notes#3]

**Comment by pbrinkmeier** [comment]
Should just one of us do all of them?
I have the time :P

**Comment by pbrinkmeier** [comment]
I will do OS/01 and OS/02 right now

**Comment by luk3b** [comment]
If you have time, go ahead :)
I'll probably do the same for RO then.

**Comment by pbrinkmeier** [comment]
Since we added the rule "no emphasis on punctuation", we should enforce it on stuff like this too:

**WRONG**

```- **and, or, xor:** binary logic operations```

**RIGHT**


```- **and**, **or**, **xor**: binary logic operations```

**Comment by luk3b** [comment]
I revised the first TI2 lecture in 1a87c70 (just a minor change), all TI2 lecture notes beginning with chapter 3 will now use the new style guide. My recently pushed chapter 3.1 is already fully styleguide-valid.

**Comment by pbrinkmeier** [comment]
I will go through it again too and (for example) replace thing like 10 x 20 with 10 &times; 20.

**Comment by luk3b** [comment]
See f2bf402
